services:
  spectra_split:
    image: spectra_split:latest
    build: 
      context: .
      dockerfile: ./spectra/services/audio/audio.Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: host
    volumes:
      - "./output/:/root/spectra/output/"